version: "3.8"
services:
  user-service:
    build: ./user-service
    container_name: user-service-container
    ports:
      - "8081:8081"

  department-service:
    build: ./department-service
    container_name: department-service-container
    ports:
      - "8082:8082"
